{
  "hash": "6b63efe462f7cfd672eba625d0053e05",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home_Ex01\"\nauthor: \"JUNCHEN LI\"\ndate: \"May 18,2026\"\ndate-modified: \"last-modified\"\nformat: html\neditor: visual\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: auto\n---\n\n# Visual Analytics for Data Discovery: Investigating Profitability, Claim Volatility, and High-Risk Segments\n\n## 1. Introduction\n\n### 1.1 Background\n\nMotor insurance is one of the major business lines in the general insurance industry. For insurers, portfolio profitability depends not only on the amount of premium collected, but also on the frequency and severity of claims. Even when the overall portfolio appears profitable, certain policyholder, vehicle, or policy segments may still generate high losses and create volatility.\n\nIn practice, insurers need to identify which customer, vehicle, and policy characteristics are associated with higher claim costs and lower profitability. Visual analytics provides a useful approach because it combines data visualization, statistical summaries, and exploratory analysis to reveal patterns that may not be obvious from aggregate figures alone.\n\nTherefore, this study applies visual analytics techniques to a motor insurance portfolio dataset to investigate profitability, claim volatility, and high-risk segments.\n\n### 1.2 Objective and Analytically Questions\n\nThe objective of this take-home exercise is to use appropriate visual analytics methods, tidyverse functions, and ggplot2 extensions to explore the profitability and volatility of a motor insurance portfolio.\n\nSpecifically, this report aims to answer the following analytically questions:\n\n-   What are the distributions of premium income, claim cost, claim frequency, and loss ratio in the insurance portfolio?\n-   How does portfolio profitability change across years?\n-   Is weak profitability mainly driven by claim frequency, claim severity, or pricing inadequacy?\n-   Which policy characteristics, such as policy type, policy status, business type, and payment frequency, are associated with higher loss ratios?\n-   Which vehicle and driver characteristics, such as fuel type, driver age, vehicle age, and vehicle value, are associated with higher claim risk?\n-   Are the observed visual patterns statistically supported by validation methods?\n\nBased on the analysis, this report provides practical insights that may support insurance pricing, underwriting, and portfolio management decisions.\n\n## 2. Getting Started\n\n### 2.1 Setting the Analytically Tools\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse,\n  janitor,\n  scales,\n  ggthemes,\n  plotly,\n  DT,\n  broom,\n  DiagrammeR\n)\n\ntheme_set(theme_minimal())\n```\n:::\n\n\nThe tidyverse family of packages is used for data importing, wrangling, transformation, and visualization. The janitor package is used to standardize column names and check data quality. The scales package is used to format percentage and currency values in charts. The plot package is used to create an interactive visualization as an extension of ggplot2. The broom package is used to present model outputs in a tidy format.\n\n### 2.2 Data Source\n\nThe dataset used in this study is a real-world motor vehicle insurance portfolio dataset from a Spanish insurance company specialized in non-life insurance. The dataset contains policy-level information, including policy characteristics, driver characteristics, vehicle characteristics, premium income, claim counts, claim costs, and exposure.\n\nThe main variables used in this analysis include total premium, total incurred claims, total claims, total exposure, policy type, policy status, payment frequency, driver age, vehicle age, fuel type, vehicle value, and circulation area.\n\n## 3.Data Wrangling\n\n### 3.1 Importing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_raw <- read_delim(\n  \"data/Dataset of motor insurance portfolio.csv\",\n  delim = \";\",\n  show_col_types = FALSE\n)\n\nglimpse(motor_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\nThe dataset is imported into the R environment using the read_delim() function because the CSV file uses semicolons as separators. The glimpse() function is used to check the structure, variable types, and sample values of the imported dataset.\n\n### 3.2 Checking Dataset Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(motor_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 354140     47\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(motor_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"insured_id\"                  \"year\"                       \n [3] \"policy_type\"                 \"policy_status\"              \n [5] \"business_type\"               \"payment_frequency\"          \n [7] \"bonus_score\"                 \"driver_age\"                 \n [9] \"vehicle_age\"                 \"age_driving_licence\"        \n[11] \"fuel_type\"                   \"vehicle_value\"              \n[13] \"seats\"                       \"power_to_weight_ratio\"      \n[15] \"vehicle_brand\"               \"municipality_type\"          \n[17] \"circulation_area\"            \"total_premium\"              \n[19] \"liability_premium\"           \"property_damage_premium\"    \n[21] \"theft_premium\"               \"fire_premium\"               \n[23] \"glass_premium\"               \"legal_protection_premium\"   \n[25] \"occupants_premium\"           \"total_claims\"               \n[27] \"liability_claims\"            \"liability_property_claims\"  \n[29] \"liability_injury_claims\"     \"property_claims\"            \n[31] \"theft_claims\"                \"fire_claims\"                \n[33] \"glass_claims\"                \"legal_protection_claims\"    \n[35] \"occupants_claims\"            \"total_incurred\"             \n[37] \"liability_incurred\"          \"liability_property_incurred\"\n[39] \"liability_injury_incurred\"   \"property_incurred\"          \n[41] \"theft_incurred\"              \"fire_incurred\"              \n[43] \"glass_incurred\"              \"legal_protection_incurred\"  \n[45] \"occupants_incurred\"          \"total_exposure\"             \n[47] \"liability_exposure\"         \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_raw %>%\n  summarise(\n    rows = n(),\n    columns = ncol(motor_raw),\n    unique_insured = n_distinct(insured_id),\n    first_year = min(year, na.rm = TRUE),\n    last_year = max(year, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    rows columns unique_insured first_year last_year\n   <int>   <int>          <int>      <dbl>     <dbl>\n1 354140      47         185678       2022      2024\n```\n\n\n:::\n:::\n\n\nThe dataset contains policy-level observations across the years 2022, 2023, and 2024. Each observation represents an insurance policy record with information on policy characteristics, vehicle characteristics, driver characteristics, premium income, claim counts, incurred claim costs, and exposure.\n\n### 3.3 Cleaning Column Names\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor <- motor_raw %>%\n  clean_names()\n\nnames(motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"insured_id\"                  \"year\"                       \n [3] \"policy_type\"                 \"policy_status\"              \n [5] \"business_type\"               \"payment_frequency\"          \n [7] \"bonus_score\"                 \"driver_age\"                 \n [9] \"vehicle_age\"                 \"age_driving_licence\"        \n[11] \"fuel_type\"                   \"vehicle_value\"              \n[13] \"seats\"                       \"power_to_weight_ratio\"      \n[15] \"vehicle_brand\"               \"municipality_type\"          \n[17] \"circulation_area\"            \"total_premium\"              \n[19] \"liability_premium\"           \"property_damage_premium\"    \n[21] \"theft_premium\"               \"fire_premium\"               \n[23] \"glass_premium\"               \"legal_protection_premium\"   \n[25] \"occupants_premium\"           \"total_claims\"               \n[27] \"liability_claims\"            \"liability_property_claims\"  \n[29] \"liability_injury_claims\"     \"property_claims\"            \n[31] \"theft_claims\"                \"fire_claims\"                \n[33] \"glass_claims\"                \"legal_protection_claims\"    \n[35] \"occupants_claims\"            \"total_incurred\"             \n[37] \"liability_incurred\"          \"liability_property_incurred\"\n[39] \"liability_injury_incurred\"   \"property_incurred\"          \n[41] \"theft_incurred\"              \"fire_incurred\"              \n[43] \"glass_incurred\"              \"legal_protection_incurred\"  \n[45] \"occupants_incurred\"          \"total_exposure\"             \n[47] \"liability_exposure\"         \n```\n\n\n:::\n:::\n\n\nThe clean_names() function from the janitor package is applied to standardise the variable names. This step makes the column names easier to reference in later data wrangling and visualisation steps.\n\n### 3.4 Checking Duplicates and Missing Values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(motor))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_summary <- motor %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(\n    cols = everything(),\n    names_to = \"variable\",\n    values_to = \"missing_count\"\n  ) %>%\n  filter(missing_count > 0) %>%\n  arrange(desc(missing_count))\n\nmissing_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  variable            missing_count\n  <chr>                       <int>\n1 fuel_type                    1287\n2 vehicle_value                 513\n3 vehicle_age                     2\n4 age_driving_licence             2\n```\n\n\n:::\n:::\n\n\nA duplicate check is conducted to ensure that the dataset does not contain repeated records. Missing values are also examined for all variables. The main variables with missing values are fuel_type, vehicle_value, vehicle_age, and age_driving_licence. Since the number of missing values is small relative to the total dataset size, these observations are removed from the analytical dataset.\n\nHanding Missing Value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_clean <- motor %>%\n  drop_na(\n    fuel_type,\n    vehicle_value,\n    vehicle_age,\n    age_driving_licence\n  )\n\ndim(motor_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 352338     47\n```\n\n\n:::\n:::\n\n\n### 3.5 Creating Analytically Insurance Metrics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_clean <- motor_clean %>%\n  mutate(\n    claim_indicator = if_else(total_claims > 0, 1, 0),\n    profit = total_premium - total_incurred,\n    loss_ratio = if_else(total_premium > 0, total_incurred / total_premium, NA_real_),\n    claim_frequency = if_else(total_exposure > 0, total_claims / total_exposure, NA_real_),\n    claim_severity = if_else(total_claims > 0, total_incurred / total_claims, NA_real_)\n  )\n```\n:::\n\n\nSeveral analytically variables are created to support the insurance portfolio analysis. Profit is calculated as total premium minus total incurred claims. Loss ratio is calculated as total incurred claims divided by total premium and is used as the main profitability measure. A higher loss ratio indicates weaker profitability.\n\nClaim frequency is calculated as total claims divided by total exposure, while claim severity is calculated as total incurred claims divided by total claims. These two variables help distinguish whether poor portfolio performance is driven by frequent claims or by large claim amounts.\n\n### 3.6 Grouping Driver Age, Vehicle Age, and Vehicle Value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_clean <- motor_clean %>%\n  mutate(\n    driver_age_group = cut(\n      driver_age,\n      breaks = c(17, 25, 35, 45, 55, 65, Inf),\n      labels = c(\"18-25\", \"26-35\", \"36-45\", \"46-55\", \"56-65\", \"66+\"),\n      right = TRUE\n    ),\n    \n    vehicle_age_group = cut(\n      vehicle_age,\n      breaks = c(-1, 5, 10, 20, 30, Inf),\n      labels = c(\"0-5\", \"6-10\", \"11-20\", \"21-30\", \"31+\"),\n      right = TRUE\n    ),\n    \n    vehicle_value_group = cut(\n      vehicle_value,\n      breaks = quantile(vehicle_value, probs = seq(0, 1, 0.2), na.rm = TRUE),\n      include.lowest = TRUE,\n      labels = c(\"Very Low\", \"Low\", \"Medium\", \"High\", \"Very High\")\n    )\n  )\n```\n:::\n\n\nDriver age, vehicle age, and vehicle value are grouped into categorical variables. This makes the visual analysis easier to interpret and allows the report to identify segment-level risk patterns more clearly.\n\nAfter the data wrangling process, the analytical dataset is ready for visual analysis. The cleaning process includes standardising column names, checking duplicates, examining missing values, removing observations with missing values in key variables, and creating insurance-specific analytical metrics.\n\nThe most important derived variables are profit, loss ratio, claim frequency, and claim severity. These variables are necessary because the original dataset only provides raw premium and claim information. By transforming the raw variables into insurance performance indicators, the analysis can evaluate not only whether the portfolio is profitable, but also why some segments are less profitable than others.\n\nLoss ratio is used as the main profitability measure. Claim frequency and claim severity are used to decompose claim risk into two components: how often claims occur and how expensive each claim is. This distinction is important because two segments may have similar loss ratios but very different risk structures.\n\n### 3.7 Analytical Workflow Map\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-27801373f12bdf17f4c8\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-27801373f12bdf17f4c8\">{\"x\":{\"diagram\":\"\\ndigraph workflow {\\n\\n  graph [\\n    layout = dot,\\n    rankdir = TB,\\n    bgcolor = transparent\\n  ]\\n\\n  node [\\n    shape = box,\\n    style = filled,\\n    fontname = Arial,\\n    fontsize = 13,\\n    color = \\\"#5DADE2\\\",\\n    fillcolor = \\\"#D6EAF8\\\",\\n    fontcolor = \\\"#102A43\\\"\\n  ]\\n\\n  edge [\\n    color = \\\"#FFFFFF\\\",\\n    arrowsize = 0.7\\n  ]\\n\\n  A [label = \\\"Raw Motor Insurance Data\\\", fillcolor = \\\"#D6EAF8\\\", color = \\\"#5DADE2\\\"]\\n  B [label = \\\"Data Cleaning\\\", fillcolor = \\\"#D5F5E3\\\", color = \\\"#58D68D\\\"]\\n  C [label = \\\"Feature Engineering\\\", fillcolor = \\\"#D5F5E3\\\", color = \\\"#58D68D\\\"]\\n\\n  C1 [label = \\\"Loss Ratio\\\", fillcolor = \\\"#FCF3CF\\\", color = \\\"#F4D03F\\\"]\\n  C2 [label = \\\"Claim Frequency\\\", fillcolor = \\\"#FCF3CF\\\", color = \\\"#F4D03F\\\"]\\n  C3 [label = \\\"Claim Severity\\\", fillcolor = \\\"#FCF3CF\\\", color = \\\"#F4D03F\\\"]\\n  C4 [label = \\\"Profit\\\", fillcolor = \\\"#FCF3CF\\\", color = \\\"#F4D03F\\\"]\\n\\n  D [label = \\\"Portfolio Trend\\\", fillcolor = \\\"#E8DAEF\\\", color = \\\"#AF7AC5\\\"]\\n  E [label = \\\"Segment Analysis\\\", fillcolor = \\\"#E8DAEF\\\", color = \\\"#AF7AC5\\\"]\\n  F [label = \\\"Policy Type / Status / Payment / Fuel / Age Groups\\\", fillcolor = \\\"#E8DAEF\\\", color = \\\"#AF7AC5\\\"]\\n\\n  G [label = \\\"Key Findings\\\", fillcolor = \\\"#FADBD8\\\", color = \\\"#EC7063\\\"]\\n  H [label = \\\"Pricing and Underwriting Implications\\\", fillcolor = \\\"#FADBD8\\\", color = \\\"#EC7063\\\"]\\n\\n  A -> B\\n  B -> C\\n\\n  C -> C1\\n  C -> C2\\n  C -> C3\\n  C -> C4\\n\\n  C1 -> D\\n  C2 -> D\\n  C3 -> D\\n\\n  C1 -> E\\n  C2 -> E\\n  C3 -> E\\n\\n  E -> F\\n  D -> G\\n  F -> G\\n  G -> H\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nThe analytical workflow map summarises how the raw motor insurance portfolio dataset is transformed into a visual analytics report. The process begins with data wrangling, including column name cleaning, duplicate checking, missing value checking, and removal of missing observations in key variables.\n\nAfter cleaning the data, several insurance-specific metrics are created, including profit, loss ratio, claim frequency, and claim severity. These variables are central to the analysis because they allow the report to evaluate not only whether the portfolio is profitable, but also whether weak performance is driven by frequent claims or expensive claims.\n\nThe workflow then moves from portfolio-level analysis to segment-level analysis and advanced visual analytics. This structure supports a clear analytical logic: first identifying the overall profitability trend, then locating high-risk segments, and finally translating the findings into pricing, underwriting, and tail-risk monitoring implications.\n\n## 4. Portfolio-Level Visual Analytics\n\nThis section uses portfolio-level visual analytics to examine the overall profitability trend of the insurance portfolio. The analysis begins with yearly aggregation because the raw dataset is policy-level, while profitability deterioration is easier to observe at the portfolio-year level.\n\nThe group_by() and summarise() functions in the dplyr package are used to aggregate total premium, total incurred claims, total claims, and exposure by year. The ggplot() function in the ggplot2 package is then used to create bar charts comparing yearly loss ratios and yearly premium-claim movements. The scales package is used to format loss ratios as percentages and monetary values as currency.\n\n::: {.observation-box}\n### Observations\n\n1. The dataset is suitable for motor insurance portfolio analysis because it contains premium income, incurred claims, claim counts, exposure, policy characteristics, driver information, and vehicle information.\n\n2. Several insurance-specific analytical variables are created, including `profit`, `loss_ratio`, `claim_frequency`, and `claim_severity`. These variables transform the raw data into a more meaningful analytical sandbox for profitability and risk analysis.\n\n3. Driver age, vehicle age, and vehicle value are grouped into categorical segments to support clearer visual comparison across risk groups.\n:::\n\n### 4.1 Overall Portfolio Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_summary <- motor_clean %>%\n  summarise(\n    number_of_records = n(),\n    unique_insured = n_distinct(insured_id),\n    total_premium = sum(total_premium, na.rm = TRUE),\n    total_incurred = sum(total_incurred, na.rm = TRUE),\n    total_claims = sum(total_claims, na.rm = TRUE),\n    total_exposure = sum(total_exposure, na.rm = TRUE),\n    overall_profit = total_premium - total_incurred,\n    overall_loss_ratio = total_incurred / total_premium,\n    overall_claim_frequency = total_claims / total_exposure,\n    overall_claim_severity = total_incurred / total_claims\n  )\n\nportfolio_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  number_of_records unique_insured total_premium total_incurred total_claims\n              <int>          <int>         <dbl>          <dbl>        <dbl>\n1            352338         184724    104379210.      73410702.        76542\n# ℹ 5 more variables: total_exposure <dbl>, overall_profit <dbl>,\n#   overall_loss_ratio <dbl>, overall_claim_frequency <dbl>,\n#   overall_claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\nThe portfolio-level summary provides the baseline for the whole analysis. At the aggregate level, the portfolio appears profitable because total premium income is higher than total incurred claims. However, this aggregate result should not be interpreted as evidence that every segment is performing well.\n\nIn insurance portfolio analysis, the overall loss ratio can hide large differences across product types, customer groups, vehicle characteristics, and policy behaviours. A portfolio can be profitable overall while still containing loss-making subgroups. Therefore, the following sections move from portfolio-level analysis to segment-level analysis to identify where profitability problems and claim volatility are concentrated.\n\n### 4.2 Yearly Trend in Loss Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_summary <- motor_clean %>%\n  group_by(year) %>%\n  summarise(\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  )\n\nyear_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n   year   premium  incurred claims exposure    profit loss_ratio claim_frequency\n  <dbl>     <dbl>     <dbl>  <dbl>    <dbl>     <dbl>      <dbl>           <dbl>\n1  2022 18596245. 12219605.  12613   41741.  6376639.      0.657           0.302\n2  2023 35125315. 23371029.  24992   82014. 11754285.      0.665           0.305\n3  2024 50657651. 37820067.  38937  125317. 12837584.      0.747           0.311\n# ℹ 1 more variable: claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(year_summary, aes(x = factor(year), y = loss_ratio)) +\n  geom_col() +\n  geom_hline(\n    yintercept = 1,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 4\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, 1.1)\n  ) +\n  labs(\n    title = \"Portfolio Loss Ratio by Year\",\n    subtitle = \"The dashed line represents the 100% break-even loss ratio\",\n    x = \"Year\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe yearly loss ratio shows a clear upward trend from 2022 to 2024. The loss ratio increased from 65.7% in 2022 to 66.5% in 2023, and then rose more noticeably to 74.7% in 2024. Since loss ratio measures incurred claims as a proportion of premium income, this increase suggests that claim costs are growing faster than premium income.\n\nAlthough the portfolio remains profitable overall because the loss ratio is still below 100%, the upward trend indicates weaker profitability over time. This is an important warning signal for the insurer because it may reflect higher claim frequency, higher claim severity, claim inflation, or insufficient premium adjustment.\n\nTherefore, the later sections examine claim frequency, claim severity, and segment-level loss ratios to identify which factors may be driving the deterioration in portfolio profitability.\n\n### 4.3 Premium Growth versus Claim Cost Growth\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_long <- year_summary %>%\n  select(year, premium, incurred) %>%\n  pivot_longer(\n    cols = c(premium, incurred),\n    names_to = \"metric\",\n    values_to = \"amount\"\n  ) %>%\n  mutate(\n    metric = recode(\n      metric,\n      \"premium\" = \"Premium Income\",\n      \"incurred\" = \"Incurred Claims\"\n    )\n  )\n\nggplot(year_long, aes(x = factor(year), y = amount, fill = metric)) +\n  geom_col(position = \"dodge\") +\n  scale_y_continuous(labels = dollar) +\n  labs(\n    title = \"Premium Income and Incurred Claims by Year\",\n    subtitle = \"Both premium and claims increased, but claim costs grew faster in 2024\",\n    x = \"Year\",\n    y = \"Amount\",\n    fill = \"Metric\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThis chart compares premium income and incurred claims across the three policy years. Both premium income and incurred claims increased from 2022 to 2024, indicating that the portfolio became larger over time. However, incurred claims increased more rapidly relative to premium income, especially in 2024.\n\nIn 2022 and 2023, the gap between premium income and incurred claims remained relatively wide. In 2024, although premium income reached its highest level, incurred claims also increased substantially. This explains why the loss ratio rose to 74.7% in 2024.\n\nFrom a portfolio management perspective, this pattern suggests that business growth alone does not guarantee stronger profitability. If claim costs grow faster than premium income, the insurer’s underwriting margin becomes thinner. Therefore, it is important to investigate whether the increase in incurred claims is driven by higher claim frequency, higher claim severity, or specific high-risk segments.\n\nBusiness growth does not necessarily improve profitability if claim costs grow faster than premium income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_growth <- year_summary %>%\n  arrange(year) %>%\n  mutate(\n    premium_growth = premium / lag(premium) - 1,\n    incurred_growth = incurred / lag(incurred) - 1\n  ) %>%\n  select(year, premium_growth, incurred_growth)\n\nyear_growth\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n   year premium_growth incurred_growth\n  <dbl>          <dbl>           <dbl>\n1  2022         NA              NA    \n2  2023          0.889           0.913\n3  2024          0.442           0.618\n```\n\n\n:::\n:::\n\n\nThe growth-rate comparison further confirms that incurred claims increased faster than premium income in 2024, which explains the deterioration in the yearly loss ratio.\n\n::: {.insight-box}\n### Portfolio-Level Insights\n\n- The portfolio remains profitable overall, but profitability weakened over time.\n\n- The yearly loss ratio increased from 65.7% in 2022 to 66.5% in 2023, and then to 74.7% in 2024.\n\n- Both premium income and incurred claims increased from 2022 to 2024, but incurred claims grew faster relative to premium income in 2024.\n\n- Business growth does not necessarily improve profitability if claim costs grow faster than premium income.\n:::\n\n## 5. Claim Distribution and Volatility\n\nThis section examines the distribution of claim costs and loss ratios to understand portfolio volatility. Insurance claim data are usually highly skewed because most policies have no or small claims, while a small number of policies generate very large losses. Therefore, distributional visualisation is important before conducting segment-level analysis.\n\nThe filter() function is used to focus on policies with positive incurred claims where appropriate. The geom_histogram() function is used to visualise claim cost and loss ratio distributions. For total incurred claims, scale_x_log10() is applied because the original claim amount distribution is highly right-skewed. A claim concentration curve is also created to assess whether a small share of high-loss policies accounts for a large share of total incurred claims.\n\n### 5.1 Distribution of Total Incurred Claims\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  motor_clean %>% filter(total_incurred > 0),\n  aes(x = total_incurred)\n) +\n  geom_histogram(\n    aes(fill = after_stat(count)),\n    bins = 50,\n    color = \"white\",\n    linewidth = 0.2\n  ) +\n  scale_fill_gradient(\n    low = \"#C7E9F1\",\n    high = \"#08589E\",\n    name = \"Number of Policies\"\n  ) +\n  scale_x_log10(\n    breaks = c(10, 100, 1000, 10000, 100000),\n    labels = dollar_format(accuracy = 1)\n  ) +\n  labs(\n    title = \"Distribution of Total Incurred Claims\",\n    subtitle = \"Darker bars indicate claim amount ranges with more policies\",\n    x = \"Total Incurred Claims, Log Scale\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe distribution of total incurred claims is shown on a log scale because claim costs are highly right-skewed in the original scale. Most policies with claims are concentrated in the lower-to-middle claim amount range, while only a small number of policies generate very large incurred claims.\n\nThis pattern is typical in insurance portfolios. Many policies either have no claim or relatively small claims, but a few large-loss policies can have a substantial effect on total incurred claims. Therefore, the mean claim amount alone may not fully represent the risk profile of the portfolio.\n\nThe log-scaled histogram makes the distribution easier to inspect by compressing extreme claim values. It shows that claim costs are not evenly distributed across policies, which motivates the following claim concentration analysis. In particular, the next section examines whether a small proportion of high-loss policies accounts for a large share of total incurred claims.\n\n### 5.2 Distribution of Loss Ratio\n\n#### 5.2.1 Claim Occurrence Overview\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaim_occurrence_summary <- motor_clean %>%\n  mutate(\n    claim_status = if_else(total_claims > 0, \"With Claims\", \"No Claims\")\n  ) %>%\n  count(claim_status) %>%\n  mutate(share = n / sum(n))\n\nclaim_occurrence_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  claim_status      n share\n  <chr>         <int> <dbl>\n1 No Claims    301862 0.857\n2 With Claims   50476 0.143\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(claim_occurrence_summary,\n       aes(x = claim_status, y = share, fill = claim_status)) +\n  geom_col(width = 0.6) +\n  geom_text(\n    aes(label = percent(share, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 4\n  ) +\n  scale_y_continuous(labels = percent, limits = c(0, 1)) +\n  scale_fill_manual(values = c(\"No Claims\" = \"#A6CEE3\", \"With Claims\" = \"#1F78B4\")) +\n  labs(\n    title = \"Share of Policies With and Without Claims\",\n    subtitle = \"Many policies have zero incurred claims, which explains the concentration at zero loss ratio\",\n    x = NULL,\n    y = \"Share of Policies\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n:::\n\n:::\n\nBefore examining the distribution of loss ratio, it is important to first separate policies with claims from policies without claims. In motor insurance portfolios, many policies do not generate any claims during the observation period. These policies have zero incurred claims and therefore a loss ratio of zero.\n\nThe claim occurrence chart shows the share of policies with and without claims. This step is necessary because a large number of zero-claim policies can dominate the original loss ratio distribution. If all policies are plotted together, the chart becomes heavily concentrated at zero and the variation among claim-generating policies becomes difficult to observe.\n\nFrom an insurance perspective, this distinction is important. Policies without claims contribute positively to profitability, while policies with claims determine the main source of claim cost and portfolio volatility. Therefore, separating claim occurrence from positive loss ratio analysis provides a clearer view of the portfolio’s risk structure.\n\n#### 5.2.2 Distribution of Positive Loss Ratio\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npositive_loss_ratio_cap <- motor_clean %>%\n  filter(loss_ratio > 0) %>%\n  summarise(cap = quantile(loss_ratio, 0.99, na.rm = TRUE)) %>%\n  pull(cap)\n\nggplot(\n  motor_clean %>% \n    filter(loss_ratio > 0, loss_ratio <= positive_loss_ratio_cap),\n  aes(x = loss_ratio)\n) +\n  geom_histogram(\n    aes(fill = after_stat(count)),\n    bins = 50,\n    color = \"white\",\n    linewidth = 0.2\n  ) +\n  scale_fill_gradient(\n    low = \"#D6EAF8\",\n    high = \"#2166AC\",\n    name = \"Number of Policies\"\n  ) +\n  scale_x_continuous(labels = percent) +\n  labs(\n    title = \"Distribution of Positive Loss Ratios\",\n    subtitle = \"Only policies with claims are included; the top 1% is excluded for readability\",\n    x = \"Loss Ratio\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nAfter separating claim occurrence, the analysis focuses only on policies with positive loss ratios. Zero-loss policies are excluded from this chart so that the distribution among claim-generating policies can be inspected more clearly. The top 1% of positive loss ratios are also excluded for readability because extreme values can stretch the x-axis and make the main distribution difficult to interpret.\n\nThe distribution of positive loss ratios remains right-skewed. This means that even among policies with claims, most policies have moderate loss ratios, while a smaller group has very high loss ratios. These high loss-ratio policies are important because their claim costs are large relative to the premium income collected.\n\nThis finding suggests that profitability risk is not evenly distributed across claim-generating policies. Some policies remain manageable from a loss ratio perspective, while others create much weaker profitability. This motivates the later segment-level analysis, where policy type, policy status, fuel type, payment frequency, driver age, and vehicle age are examined to identify whether high loss-ratio policies are concentrated in specific groups.\n\nOverall, this two-step analysis provides a clearer interpretation than plotting the original loss ratio distribution alone. The first chart explains why the original distribution is concentrated at zero, while the second chart reveals the shape of the loss ratio distribution among policies that actually generate claims.\n\nThis approach is useful for insurance visual analytics because it separates claim occurrence risk from claim profitability risk. Claim occurrence shows whether a policy generates a claim, while positive loss ratio shows how severe the financial impact is once a claim occurs. This distinction supports the later frequency-severity and segment-level analysis.\n\n### 5.3 Claim Concentration and Tail Risk\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaim_concentration <- motor_clean %>%\n  filter(total_incurred > 0) %>%\n  arrange(desc(total_incurred)) %>%\n  mutate(\n    claim_rank = row_number(),\n    claim_percentile = claim_rank / n(),\n    cumulative_incurred = cumsum(total_incurred),\n    cumulative_share = cumulative_incurred / sum(total_incurred)\n  )\n\nclaim_concentration_summary <- claim_concentration %>%\n  summarise(\n    top_1_percent_share = sum(total_incurred[claim_percentile <= 0.01]) / sum(total_incurred),\n    top_5_percent_share = sum(total_incurred[claim_percentile <= 0.05]) / sum(total_incurred),\n    top_10_percent_share = sum(total_incurred[claim_percentile <= 0.10]) / sum(total_incurred)\n  )\n\nclaim_concentration_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  top_1_percent_share top_5_percent_share top_10_percent_share\n                <dbl>               <dbl>                <dbl>\n1               0.210               0.409                0.530\n```\n\n\n:::\n:::\n\n\nThe concentration summary further quantifies the tail-risk pattern. The largest 1%, 5%, and 10% of claim policies explain a disproportionate share of total incurred claims. This confirms that a small number of large-loss policies has a large effect on portfolio-level claim costs.\n\nFor example, the largest 1% of claim policies account for approximately 21% of total incurred claims, while the largest 10% account for approximately 53%. This confirms that claim costs are highly concentrated among a small group of high-loss policies.\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop10_share <- claim_concentration %>%\n  filter(claim_percentile <= 0.10) %>%\n  summarise(share = max(cumulative_share)) %>%\n  pull(share)\n\nggplot(claim_concentration,\n       aes(x = claim_percentile, y = cumulative_share)) +\n  geom_line(color = \"#08589E\", linewidth = 1.1) +\n  geom_vline(xintercept = 0.10, linetype = \"dashed\") +\n  geom_hline(yintercept = top10_share, linetype = \"dashed\") +\n  annotate(\n    \"text\",\n    x = 0.28,\n    y = top10_share + 0.04,\n    label = paste0(\"Top 10% of claim policies account for \",\n                   percent(top10_share, accuracy = 0.1),\n                   \" of incurred claims\"),\n    size = 3.5\n  ) +\n  scale_x_continuous(labels = percent) +\n  scale_y_continuous(labels = percent) +\n  labs(\n    title = \"Claim Concentration Curve\",\n    subtitle = \"A small share of high-loss policies contributes a large share of total incurred claims\",\n    x = \"Share of Claim Policies, Ordered by Claim Size\",\n    y = \"Cumulative Share of Total Incurred Claims\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe claim concentration curve shows the cumulative share of total incurred claims contributed by claim policies ordered from the largest claim amount to the smallest. The curve rises steeply at the beginning, which means that a relatively small proportion of high-loss policies accounts for a large share of total incurred claims.\n\nThis result provides clear evidence of claim concentration. In other words, portfolio volatility is not only driven by the average claim amount, but also by a small number of large-loss policies. These high-loss policies can have a material impact on total incurred claims and may weaken portfolio profitability even when most policies generate small or moderate claims.\n\nFrom an insurance portfolio management perspective, this finding is important because it highlights the need for tail-risk monitoring. The insurer should not only monitor average claim frequency and severity, but also examine the characteristics of large-loss policies. For example, further analysis could investigate whether high-loss claims are concentrated in specific policy types, vehicle age groups, fuel types, regions, or payment frequency groups.\n\n### 5.4 Frequency-Severity Decomposition by Year\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_fs <- year_summary %>%\n  select(year, claim_frequency, claim_severity) %>%\n  pivot_longer(\n    cols = c(claim_frequency, claim_severity),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) %>%\n  mutate(\n    metric = recode(\n      metric,\n      \"claim_frequency\" = \"Claim Frequency\",\n      \"claim_severity\" = \"Claim Severity\"\n    ),\n    label = case_when(\n      metric == \"Claim Frequency\" ~ round(value, 3) %>% as.character(),\n      metric == \"Claim Severity\" ~ dollar(value, accuracy = 1)\n    )\n  )\n\nggplot(year_fs, aes(x = factor(year), y = value, group = metric)) +\n  geom_line(linewidth = 1, color = \"#08589E\") +\n  geom_point(size = 2.5, color = \"#08589E\") +\n  geom_text(\n    aes(label = label),\n    vjust = -0.8,\n    size = 3.5\n  ) +\n  facet_wrap(~ metric, scales = \"free_y\") +\n  labs(\n    title = \"Frequency-Severity Decomposition by Year\",\n    subtitle = \"Claim frequency increased steadily, while claim severity rebounded in 2024\",\n    x = \"Year\",\n    y = NULL\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nFrequency-severity decomposition is used to understand why the portfolio loss ratio changed over time. Claim frequency measures how often claims occur per unit of exposure, while claim severity measures the average incurred claim cost per claim. This decomposition is important because the same loss ratio increase can be caused by more frequent claims, more expensive claims, or both.\n\nThe result shows that claim frequency increased steadily from 2022 to 2024. This suggests that claims became more frequent over time. Claim severity shows a different pattern: it decreased in 2023 but increased again in 2024. Therefore, the deterioration in 2024 profitability appears to be driven by both higher claim frequency and a rebound in claim severity.\n\nThis finding helps explain the earlier yearly loss ratio result. The portfolio loss ratio increased to 74.7% in 2024 because claim costs became heavier relative to premium income. From an insurance management perspective, this means that the insurer should monitor both claim occurrence and average claim size. If only loss ratio is analysed, the underlying source of deterioration may be unclear.\n\nThe 2024 profitability deterioration is not only a premium issue; it is also related to higher claim frequency and a rebound in claim severity.\n\n::: {.insight-box}\n### Claim Volatility Insights\n\n- Claim costs are highly right-skewed, meaning that most policies generate small or no claims, while a small number of policies generate very large losses.\n\n- The original loss ratio distribution is heavily concentrated at zero because many policies have no incurred claims. Separating claim occurrence from positive loss ratio distribution provides a clearer view of claim-generating policies.\n\n- The claim concentration curve shows that portfolio volatility is strongly influenced by tail-risk observations.\n\n- Frequency-severity decomposition shows that the 2024 deterioration is related to both higher claim frequency and a rebound in claim severity.\n:::\n\n## 6. Segment-Level Profitability Analysis\n\nThis section applies bivariate visual analytics to compare profitability and claim risk across key policy, vehicle, and driver segments. The main objective is to identify whether high loss ratios are concentrated in specific groups.\n\nFor each segment, the data are aggregated using group_by() and summarise(). Loss ratio, claim frequency, and claim severity are calculated at the segment level. Bar charts created using geom_col() are used to compare loss ratios across categories. In several charts, benchmark lines are added to represent either the 100% break-even loss ratio or the overall portfolio loss ratio. This makes it easier to identify segments with weaker-than-average profitability.\n\n### 6.1 Policy Type and Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_type_summary <- motor_clean %>%\n  group_by(policy_type) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(loss_ratio))\n\npolicy_type_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 10\n  policy_type      n   premium  incurred claims exposure    profit loss_ratio\n  <chr>        <int>     <dbl>     <dbl>  <dbl>    <dbl>     <dbl>      <dbl>\n1 COMP_N       16012 10212915.  9546432.  12749   12221.   666484.      0.935\n2 COMP_E       90320 35335541. 26128628.  26382   64417.  9206913.      0.739\n3 TPG          35988  8106186.  5638790.   5108   24656.  2467396.      0.696\n4 CC          204317 49715151. 31545729.  31800  144010. 18169422.      0.635\n5 TP            5701  1009417.   551123.    503    3768.   458294.      0.546\n# ℹ 2 more variables: claim_frequency <dbl>, claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n### 6.1.1 loss ratio across policy types\n::: panel-tabset\n### The Code\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(policy_type_summary,\n       aes(\n         x = reorder(policy_type, loss_ratio),\n         y = loss_ratio,\n         fill = policy_type == \"COMP_N\"\n       )) +\n  geom_col() +\n  geom_hline(\n    yintercept = 1,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    hjust = -0.1,\n    size = 3.8\n  ) +\n  coord_flip() +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D73027\", \"FALSE\" = \"#2C7FB8\"),\n    guide = \"none\"\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, 1.1)\n  ) +\n  labs(\n    title = \"Loss Ratio by Policy Type\",\n    subtitle = \"COMP_N has the weakest profitability and is closest to the break-even threshold\",\n    x = \"Policy Type\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe first chart compares loss ratio across policy types. The result shows clear differences in profitability across insurance products. COMP_N has the highest loss ratio at 93.5%, followed by COMP_E at 73.9% and TPG at 69.6%. In contrast, TP has the lowest loss ratio at 54.6%, making it the most profitable policy type among the five groups.\n\nAlthough all policy types remain below the 100% break-even threshold, COMP_N is much closer to this threshold than the other policy types. This means that COMP_N has a thinner underwriting margin and may be more vulnerable to future increases in claim costs. Therefore, COMP_N should be examined further to understand whether its weaker profitability is caused by claim frequency, claim severity, or insufficient premium pricing.\n\n### 6.2.2 claim frequency across policy types\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(policy_type_summary,\n       aes(\n         x = reorder(policy_type, claim_frequency),\n         y = claim_frequency,\n         fill = policy_type == \"COMP_N\"\n       )) +\n  geom_col() +\n  geom_text(\n    aes(label = round(claim_frequency, 2)),\n    hjust = -0.1,\n    size = 3.8\n  ) +\n  coord_flip() +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D73027\", \"FALSE\" = \"#2C7FB8\"),\n    guide = \"none\"\n  ) +\n  scale_y_continuous(\n    limits = c(0, max(policy_type_summary$claim_frequency) * 1.15)\n  ) +\n  labs(\n    title = \"Claim Frequency by Policy Type\",\n    subtitle = \"COMP_N generates claims much more often per unit of exposure\",\n    x = \"Policy Type\",\n    y = \"Claim Frequency\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe second chart compares claim frequency across policy types. This helps explain whether the weaker profitability of COMP_N is mainly driven by more frequent claims. The result shows that COMP_N has a claim frequency of 1.04, which is much higher than all other policy types. COMP_E has the second highest claim frequency at 0.41, while TP has the lowest claim frequency at 0.13.\n\nThis indicates that COMP_N is a frequency-driven risk segment. In other words, COMP_N does not only have the highest loss ratio, but also generates claims much more often per unit of exposure. This helps explain why its profitability is weaker than other policy types.\n\nTaken together, the two charts show that COMP_N is the most concerning policy type in the portfolio. It combines the highest loss ratio with the highest claim frequency, which suggests that its weak profitability is mainly driven by frequent claim occurrence. From an insurance management perspective, this segment should be prioritised for further pricing and underwriting review.\n\nThis combined analysis is more useful than examining loss ratio alone. A high loss ratio shows weaker profitability, but claim frequency helps explain the source of that weakness. For COMP_N, the main issue appears to be claim occurrence rather than only claim size. Therefore, the insurer may need to review the customer profile, vehicle characteristics, coverage design, and pricing assumptions associated with this policy type.\n\n### 6.2 Policy Status and Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_status_summary <- motor_clean %>%\n  group_by(policy_status) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    .groups = \"drop\"\n  )\n\npolicy_status_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  policy_status      n   premium  incurred    profit loss_ratio\n  <chr>          <int>     <dbl>     <dbl>     <dbl>      <dbl>\n1 A             314181 94752018. 61092259. 33659759.      0.645\n2 C              38157  9627192. 12318443. -2691250.      1.28 \n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(policy_status_summary,\n       aes(x = policy_status, y = loss_ratio)) +\n  geom_col() +\n  geom_hline(\n    yintercept = 1,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 4\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, max(policy_status_summary$loss_ratio) * 1.15)\n  ) +\n  labs(\n    title = \"Loss Ratio by Policy Status\",\n    subtitle = \"The dashed line represents the 100% break-even loss ratio\",\n    x = \"Policy Status\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe dashed horizontal line represents the 100% break-even loss ratio. Segments above this line are loss-making because claim costs exceed premium income.\n\nPolicy status is analysed to examine whether active and closed or cancelled policies show different profitability patterns. This is useful because policy status may reflect differences in customer behavior, policy duration, renewal decisions, or adverse claim experience.\n\nThe result shows a clear profitability difference between policy status groups. Policies with status A have a loss ratio of 64.5%, which indicates that this group remains profitable because incurred claims are lower than premium income. In contrast, policies with status C have a loss ratio of 128.0%, meaning that claim costs exceed premium income for this segment.\n\nThis is an important finding because policy status is not only an administrative variable, but also appears to be strongly associated with profitability. The result suggests that status C policies may contain worse claim experience or adverse policy behavior. From a portfolio management perspective, this segment should be prioritized for further investigation, especially to understand whether cancellation or closure is related to high claim activity.\n\n### 6.3 Payment Frequency and Risk Profile\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayment_summary <- motor_clean %>%\n  group_by(payment_frequency) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(loss_ratio))\n\npayment_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 10\n  payment_frequency      n   premium  incurred claims exposure profit loss_ratio\n  <chr>              <int>     <dbl>     <dbl>  <dbl>    <dbl>  <dbl>      <dbl>\n1 S                  50655 15397607. 12424121.  12105   36000. 2.97e6      0.807\n2 Q                  15309  6676909.  5101256.   4740   10202. 1.58e6      0.764\n3 A                 286374 82304695. 55885324.  59697  202870. 2.64e7      0.679\n# ℹ 2 more variables: claim_frequency <dbl>, claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n### 6.3.1 loss ratio by payment frequency\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(payment_summary,\n       aes(x = payment_frequency, y = loss_ratio,\n           fill = loss_ratio > portfolio_summary$overall_loss_ratio)) +\n  geom_col() +\n  geom_hline(\n    yintercept = portfolio_summary$overall_loss_ratio,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 4\n  ) +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D73027\", \"FALSE\" = \"#2C7FB8\"),\n    guide = \"none\"\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, max(payment_summary$loss_ratio) * 1.15)\n  ) +\n  labs(\n    title = \"Loss Ratio by Payment Frequency\",\n    subtitle = \"The dashed line represents the overall portfolio loss ratio\",\n    x = \"Payment Frequency\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe loss ratio by payment frequency shows that profitability differs across payment behaviour groups. Annual payment policies have the lowest loss ratio at 67.9%, while quarterly payment policies have a higher loss ratio at 76.4%. Semi-annual payment policies have the highest loss ratio at 80.7%, indicating the weakest profitability among the three groups.\n\nThis pattern suggests that payment frequency is associated with different risk profiles. Policies paid annually appear to be more profitable, while policies paid quarterly or semi-annually show weaker profitability. One possible explanation is that payment frequency may capture differences in customer characteristics, policy duration, or financial behaviour. However, this result should be interpreted as an association rather than a causal relationship.\n\nFrom an insurance management perspective, payment frequency can be useful as a segmentation variable for portfolio monitoring. If non-annual payment groups consistently show higher loss ratios, the insurer may need to examine whether these customers also differ in policy type, claim frequency, exposure, or cancellation behaviour.\n\nThis finding also connects with the later risk heatmap, where payment frequency is combined with policy type to identify whether high loss ratios are concentrated in specific product-payment combinations.\n\n### 6.4 Fuel Type and Claim Risk\nFor fuel type, the analysis compares loss ratio, claim frequency, and claim severity within the same visualisation. The pivot_longer() function is used to transform the segment-level summary table into a long format, so that the three metrics can be displayed using facet_wrap(). This design allows the comparison of profitability, claim occurrence, and average claim size side by side.\n\nThis approach is useful because a higher loss ratio can be caused by either higher claim frequency or higher claim severity. By showing all three metrics together, the chart helps identify whether fuel-type risk is frequency-driven or severity-driven.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuel_summary <- motor_clean %>%\n  group_by(fuel_type) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  )\n\nfuel_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 10\n  fuel_type      n   premium  incurred claims exposure    profit loss_ratio\n  <chr>      <int>     <dbl>     <dbl>  <dbl>    <dbl>     <dbl>      <dbl>\n1 D         226140 71557182. 52298147.  54546  159633. 19259035.      0.731\n2 G         126198 32822028. 21112554.  21996   89439. 11709474.      0.643\n# ℹ 2 more variables: claim_frequency <dbl>, claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuel_summary <- motor_clean %>%\n  group_by(fuel_type) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  )\n\nfuel_long <- fuel_summary %>%\n  select(fuel_type, loss_ratio, claim_frequency, claim_severity) %>%\n  pivot_longer(\n    cols = c(loss_ratio, claim_frequency, claim_severity),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) %>%\n  mutate(\n    metric = recode(\n      metric,\n      \"claim_frequency\" = \"Claim Frequency\",\n      \"claim_severity\" = \"Claim Severity\",\n      \"loss_ratio\" = \"Loss Ratio\"\n    ),\n    label = case_when(\n      metric == \"Claim Frequency\" ~ as.character(round(value, 3)),\n      metric == \"Claim Severity\" ~ dollar(value, accuracy = 1),\n      metric == \"Loss Ratio\" ~ percent(value, accuracy = 0.1)\n    )\n  )\n\nggplot(fuel_long, aes(x = fuel_type, y = value, fill = fuel_type)) +\n  geom_col(width = 0.7) +\n  geom_text(\n    aes(label = label),\n    vjust = -0.35,\n    size = 3.6\n  ) +\n  facet_wrap(~ metric, scales = \"free_y\") +\n  scale_fill_manual(\n    values = c(\n      \"D\" = \"#D95F02\",\n      \"G\" = \"#1B9E77\"\n    )\n  ) +\n  labs(\n    title = \"Fuel Type and Claim Risk\",\n    subtitle = \"Diesel vehicles show weaker profitability mainly because of higher claim frequency\",\n    x = \"Fuel Type\",\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    strip.text = element_text(face = \"bold\"),\n    plot.title = element_text(face = \"bold\")\n  )\n```\n:::\n\n:::\n\nThe fuel type analysis compares claim frequency, claim severity, and loss ratio between diesel and gasoline vehicles. Diesel vehicles have a higher claim frequency of 0.342, compared with 0.246 for gasoline vehicles. Diesel vehicles also have a higher loss ratio of 73.1%, while gasoline vehicles have a lower loss ratio of 64.3%.\n\nHowever, claim severity is almost identical between the two groups. Diesel vehicles have an average claim severity of $959, while gasoline vehicles have an average claim severity of $960. This means that diesel vehicles do not generate more expensive claims on average. Instead, they generate claims more often.\n\nThis finding suggests that the weaker profitability of diesel vehicles is mainly frequency-driven rather than severity-driven. From an underwriting perspective, this is useful because frequency-driven risk and severity-driven risk require different management responses. For diesel vehicles, the insurer may need to review vehicle usage intensity, customer driving patterns, policy type composition, or pricing adequacy, rather than focusing only on repair cost per claim.\n\n### 6.5 Driver Age and Loss Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndriver_age_summary <- motor_clean %>%\n  group_by(driver_age_group) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  )\n\ndriver_age_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 10\n  driver_age_group      n   premium  incurred claims exposure  profit loss_ratio\n  <fct>             <int>     <dbl>     <dbl>  <dbl>    <dbl>   <dbl>      <dbl>\n1 18-25              1764  1015512.   638123.    560    1146.  3.77e5      0.628\n2 26-35             48610 14961658. 10976512.  12380   33753.  3.99e6      0.734\n3 36-45            102682 29134727. 21102352.  23031   72494.  8.03e6      0.724\n4 46-55             87607 26663777. 18062129.  18758   61892.  8.60e6      0.677\n5 56-65             73788 21867067. 14831588.  14909   52976.  7.04e6      0.678\n6 66+               37887 10736471.  7799998.   6904   26810.  2.94e6      0.726\n# ℹ 2 more variables: claim_frequency <dbl>, claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(driver_age_summary,\n       aes(\n         x = driver_age_group,\n         y = loss_ratio,\n         fill = loss_ratio > portfolio_summary$overall_loss_ratio\n       )) +\n  geom_col() +\n  geom_hline(\n    yintercept = portfolio_summary$overall_loss_ratio,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 3.8\n  ) +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D73027\", \"FALSE\" = \"#2C7FB8\"),\n    guide = \"none\"\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, max(driver_age_summary$loss_ratio) * 1.15)\n  ) +\n  labs(\n    title = \"Loss Ratio by Driver Age Group\",\n    subtitle = \"The dashed line represents the overall portfolio loss ratio\",\n    x = \"Driver Age Group\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe loss ratio by driver age group shows that profitability differs across age segments, but the relationship is not strictly linear. The youngest group, aged 18–25, has the lowest loss ratio at 62.8%, while the 26–35 group has the highest loss ratio at 73.4%. The 36–45 and 66+ groups also show relatively high loss ratios at 72.4% and 72.6%, respectively.\n\nThis result suggests that driver age is associated with portfolio profitability, but younger drivers are not necessarily the weakest-performing group in this dataset. Instead, the highest loss ratios appear among middle-younger drivers and older drivers. This may reflect differences in vehicle usage, driving exposure, policy type composition, or customer behaviour across age groups.\n\nFrom an underwriting perspective, driver age should not be interpreted in isolation. Although the 26–35 and 66+ groups show weaker profitability, further analysis would be needed to determine whether this is caused by higher claim frequency, higher claim severity, or other correlated factors such as vehicle value, policy type, or driving licence age. Therefore, driver age is useful as a segmentation variable, but it should be combined with other risk indicators for pricing and underwriting decisions.\n\n### 6.6 Vehicle Age and Loss Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvehicle_age_summary <- motor_clean %>%\n  group_by(vehicle_age_group) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    profit = premium - incurred,\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims,\n    .groups = \"drop\"\n  )\n\nvehicle_age_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 10\n  vehicle_age_group      n   premium  incurred claims exposure profit loss_ratio\n  <fct>              <int>     <dbl>     <dbl>  <dbl>    <dbl>  <dbl>      <dbl>\n1 0-5                 6711  3032734.  2267816.   2074    4312. 7.65e5      0.748\n2 6-10               25070  7929690.  5600949.   6161   17100. 2.33e6      0.706\n3 11-20              96151 27316652. 20779045.  22360   67844. 6.54e6      0.761\n4 21-30             100412 29452827. 20033514.  21672   71327. 9.42e6      0.680\n5 31+               123994 36647308. 24729377.  24275   88488. 1.19e7      0.675\n# ℹ 2 more variables: claim_frequency <dbl>, claim_severity <dbl>\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vehicle_age_summary,\n       aes(\n         x = vehicle_age_group,\n         y = loss_ratio,\n         fill = loss_ratio > portfolio_summary$overall_loss_ratio\n       )) +\n  geom_col() +\n  geom_hline(\n    yintercept = portfolio_summary$overall_loss_ratio,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.3,\n    size = 3.8\n  ) +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D73027\", \"FALSE\" = \"#2C7FB8\"),\n    guide = \"none\"\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0, max(vehicle_age_summary$loss_ratio) * 1.15)\n  ) +\n  labs(\n    title = \"Loss Ratio by Vehicle Age Group\",\n    subtitle = \"The dashed line represents the overall portfolio loss ratio\",\n    x = \"Vehicle Age Group\",\n    y = \"Loss Ratio\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe loss ratio by vehicle age group shows that profitability differs across vehicle age segments, but the relationship is not strictly linear. Vehicles aged 11–20 years have the highest loss ratio at 76.1%, followed by newer vehicles aged 0–5 years at 74.8%. In contrast, older vehicles aged 21–30 years and 31+ years have lower loss ratios at 68.0% and 67.5%, respectively.\n\nThis result suggests that vehicle age is associated with profitability, but older vehicles are not necessarily the weakest-performing group in this portfolio. The higher loss ratio for vehicles aged 11–20 years may reflect higher claim frequency, maintenance-related risk, or different policyholder behaviour. The relatively high loss ratio for newer vehicles may be related to higher repair costs, higher vehicle values, or more expensive replacement parts.\n\nFrom an underwriting perspective, vehicle age should be analysed together with claim frequency and claim severity. If newer vehicles have higher loss ratios because of higher repair costs, the risk is severity-driven. If middle-aged vehicles have higher loss ratios because they claim more often, the risk is frequency-driven. Therefore, vehicle age is useful as a segmentation variable, but further frequency-severity analysis is needed before making pricing or underwriting decisions.\n\n::: {.insight-box}\n### Segment-Level Insights\n\n- `COMP_N` is the most concerning policy type because it has both the highest loss ratio at 93.5% and the highest claim frequency at 1.04.\n\n- Policy status `C` is a clear loss-making segment, with a loss ratio of 128.0%. This means claim costs exceed premium income for this group.\n\n- Non-annual payment groups show weaker profitability. Annual payment policies have the lowest loss ratio at 67.9%, while quarterly and semi-annual payment policies have higher loss ratios of 76.4% and 80.7%.\n\n- Diesel vehicles have weaker profitability mainly because of higher claim frequency. Claim severity is almost identical between diesel and gasoline vehicles, suggesting that fuel-type risk is frequency-driven rather than severity-driven.\n\n- Driver age and vehicle age show non-linear profitability patterns. Therefore, they should be interpreted together with other risk indicators rather than in isolation.\n:::\n\n## 7. Advanced Visual Analytics\n\nThis section extends the analysis beyond one-variable bar charts by using advanced visual analytics techniques. The purpose is to identify high-risk segment combinations and to provide a more interactive view of portfolio performance.\n\nA heatmap is used to combine policy type and payment frequency in one visualisation. This helps identify whether high loss ratios are concentrated in specific product-payment combinations. A quadrant chart is then used to compare claim frequency and loss ratio at the same time, with bubble size representing premium volume. Finally, an interactive plotly chart is created to allow users to inspect detailed segment-level information through tooltips.\n\n### 7.1 Risk Heatmap by Policy Type and Payment Frequency\n\nThe risk heatmap is created by grouping the data by policy type and payment frequency. The geom_tile() function is used to display each segment as a cell, while fill colour represents the segment-level loss ratio. The geom_text() function is used to place the loss ratio value inside each cell.\n\nThis visual design is useful because it allows two categorical variables to be examined simultaneously. It can reveal high-risk combinations that may be hidden when policy type and payment frequency are analysed separately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrisk_heatmap <- motor_clean %>%\n  group_by(policy_type, payment_frequency) %>%\n  summarise(\n    n = n(),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    .groups = \"drop\"\n  )\n\nrisk_heatmap\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 9\n   policy_type payment_frequency      n   premium  incurred claims exposure\n   <chr>       <chr>              <int>     <dbl>     <dbl>  <dbl>    <dbl>\n 1 CC          A                 164703 38211302. 22375541.  23723  116286.\n 2 CC          Q                   8428  3259610.  2606788.   2133    5497.\n 3 CC          S                  31186  8244239.  6563400.   5944   22227.\n 4 COMP_E      A                  75353 28897211. 21404901.  21470   53730.\n 5 COMP_E      Q                   3894  1988305.  1416589.   1462    2772.\n 6 COMP_E      S                  11073  4450025.  3307138.   3450    7915.\n 7 COMP_N      A                  13367  8536719.  7901252.  10469   10212.\n 8 COMP_N      Q                    813   574516.   446706.    699     617.\n 9 COMP_N      S                   1832  1101681.  1198474.   1581    1392.\n10 TP          A                   4727   778953.   477224.    396    3135.\n11 TP          Q                    170    65048.    10326.     17     106.\n12 TP          S                    804   165416.    63573.     90     527.\n13 TPG         A                  28224  5880510.  3726406.   3639   19506.\n14 TPG         Q                   2004   789430.   620848.    429    1210.\n15 TPG         S                   5760  1436246.  1291536.   1040    3940.\n# ℹ 2 more variables: loss_ratio <dbl>, claim_frequency <dbl>\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrisk_heatmap <- risk_heatmap %>%\n  mutate(\n    risk_label = if_else(loss_ratio > 1, \"Loss-making\", \"Profitable\")\n  )\n\nggplot(risk_heatmap,\n       aes(x = payment_frequency, y = policy_type, fill = loss_ratio)) +\n  geom_tile(color = \"white\") +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    size = 3.5\n  ) +\n  scale_fill_gradient(\n    low = \"#FEE5D9\",\n    high = \"#CB181D\",\n    labels = percent,\n    name = \"Loss Ratio\"\n  ) +\n  labs(\n    title = \"Risk Heatmap by Policy Type and Payment Frequency\",\n    subtitle = \"COMP_N with semi-annual payment is loss-making with a loss ratio above 100%\",\n    x = \"Payment Frequency\",\n    y = \"Policy Type\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe risk heatmap provides a segment-level view of profitability by combining policy type and payment frequency. Compared with separate bar charts, this heatmap is more informative because it shows whether high loss ratios are concentrated in specific product-payment combinations.\n\nThe most important finding is that the COMP_N and semi-annual payment segment has the highest loss ratio at 108.8%. Since this value is above the 100% break-even threshold, this segment is loss-making: claim costs exceed premium income. This is a stronger warning signal than the overall COMP_N loss ratio because it shows that the profitability problem is especially concentrated in the semi-annual payment subgroup.\n\nThe heatmap also shows that TPG with semi-annual payment has a relatively high loss ratio of 89.9%, while CC policies with quarterly and semi-annual payments have loss ratios close to 80%. These results suggest that payment frequency may interact with policy type. In other words, the risk associated with payment frequency is not the same for every policy type.\n\nFrom an insurance management perspective, this heatmap helps prioritise underwriting and pricing review. Instead of treating all COMP_N policies as equally risky, the insurer can focus first on the COMP_N and semi-annual payment segment. This demonstrates the value of visual analytics: it helps identify more specific high-risk combinations that may be hidden in one-variable summaries.\n\nOverall, the heatmap reveals that profitability problems are not evenly distributed across the portfolio. The highest-risk segment is not simply COMP_N as a whole, but specifically COMP_N policies with semi-annual payment frequency.\n\n::: {.warning-box}\n### Key Risk Segment\n\n- The heatmap identifies `COMP_N + S` as the highest-risk segment.\n\n- `COMP_N + S` has a loss ratio of 108.8%, which is above the 100% break-even threshold.\n\n- This means that claim costs exceed premium income for this specific product-payment combination.\n\n- The result shows that the profitability problem is not only `COMP_N` as a broad policy type, but more specifically `COMP_N` with semi-annual payment frequency.\n:::\n\n### 7.2 Premium Adequacy Quadrant\n\nThe premium adequacy quadrant is created to compare claim frequency and loss ratio at the same time. Each point represents one policy type. The x-axis shows claim frequency, the y-axis shows loss ratio, and bubble size represents premium volume.\n\nThe horizontal dashed line represents the overall portfolio loss ratio, while the vertical dashed line represents the overall portfolio claim frequency. These reference lines divide the plot into different risk zones. Policy types in the upper-right area have both above-average claim frequency and above-average loss ratio, making them priority segments for pricing and underwriting review.\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(policy_type_summary,\n       aes(\n         x = claim_frequency,\n         y = loss_ratio,\n         size = premium,\n         label = policy_type\n       )) +\n  geom_point(\n    alpha = 0.75,\n    color = \"#2C7FB8\"\n  ) +\n  geom_text(\n    vjust = -1,\n    size = 3.8\n  ) +\n  geom_hline(\n    yintercept = portfolio_summary$overall_loss_ratio,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = portfolio_summary$overall_claim_frequency,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0.50, 1.00)\n  ) +\n  scale_x_continuous(\n    limits = c(0, max(policy_type_summary$claim_frequency) * 1.15)\n  ) +\n  scale_size_continuous(labels = dollar) +\n  labs(\n    title = \"Premium Adequacy Quadrant by Policy Type\",\n    subtitle = \"Loss ratio versus claim frequency, with bubble size representing premium volume\",\n    x = \"Claim Frequency\",\n    y = \"Loss Ratio\",\n    size = \"Premium\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\nThe premium adequacy quadrant provides an integrated view of policy type performance. The x-axis represents claim frequency, the y-axis represents loss ratio, and the bubble size represents premium volume. The dashed vertical line shows the overall portfolio claim frequency, while the dashed horizontal line shows the overall portfolio loss ratio. Therefore, policy types above the horizontal line have weaker-than-average profitability, and policy types to the right of the vertical line have higher-than-average claim frequency.\n\nThe chart shows that COMP_N is located in the upper-right area. This means that COMP_N has both above-average claim frequency and above-average loss ratio. It is the most concerning policy type because it combines frequent claim occurrence with weak profitability. COMP_E is also above both portfolio averages, although its risk level is less extreme than COMP_N.\n\nIn contrast, CC and TP are located in the lower-left area, meaning that they have both below-average claim frequency and below-average loss ratio. These policy types appear to be more stable and more profitable. TPG is close to the average loss ratio but has relatively low claim frequency, suggesting that its profitability issue may be less frequency-driven.\n\nFrom an insurance management perspective, this quadrant chart is more useful than a simple bar chart because it separates frequency-driven risk from overall profitability. It shows that COMP_N should be prioritised for underwriting and pricing review, while CC and TP appear to be stronger-performing segments.\n\nOverall, the quadrant chart confirms that COMP_N is the most important high-risk segment because it combines high claim frequency, high loss ratio, and meaningful premium volume. This makes it a priority candidate for pricing review and underwriting refinement.\n\n### 7.3 Interactive Segment-Level Visualisation\n\nThe interactive visualisation is created using ggplotly() from the plotly package. The original ggplot object is converted into an interactive chart, allowing users to hover over each point and inspect detailed information such as loss ratio, claim frequency, claim severity, premium income, and profit.\n\nThis is useful for exploratory visual analytics because insurance portfolio review often requires comparing multiple performance indicators at the same time. The interactive chart allows users to move from a broad visual pattern to detailed segment-level information.\n\n::: panel-tabset\n### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-9f6eb9f25ed3ce724a3a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9f6eb9f25ed3ce724a3a\">{\"x\":{\"data\":[{\"x\":[1.0432368290197165,0.40954996046099085,0.20717472006599652,0.22081766267348227,0.13350217892251501],\"y\":[0.93474107917131921,0.73944327795500264,0.69561569282419511,0.63452947667216786,0.54598143166807545],\"text\":[\"Policy Type: COMP_N <br>Loss Ratio: 93.5% <br>Claim Frequency: 1.043 <br>Claim Severity: $748.80 <br>Premium: $10,212,915 <br>Profit: $666,484\",\"Policy Type: COMP_E <br>Loss Ratio: 73.9% <br>Claim Frequency: 0.41 <br>Claim Severity: $990.40 <br>Premium: $35,335,541 <br>Profit: $9,206,913\",\"Policy Type: TPG <br>Loss Ratio: 69.6% <br>Claim Frequency: 0.207 <br>Claim Severity: $1,103.91 <br>Premium: $8,106,186 <br>Profit: $2,467,396\",\"Policy Type: CC <br>Loss Ratio: 63.5% <br>Claim Frequency: 0.221 <br>Claim Severity: $992.00 <br>Premium: $49,715,151 <br>Profit: $18,169,422\",\"Policy Type: TP <br>Loss Ratio: 54.6% <br>Claim Frequency: 0.134 <br>Claim Severity: $1,095.67 <br>Premium: $1,009,417 <br>Profit: $458,294\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(44,127,184,1)\",\"opacity\":0.75,\"size\":[11.994269795760291,19.644154255942624,10.993056700490754,22.677165354330711,3.7795275590551185],\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(44,127,184,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.0432368290197165,0.40954996046099085,0.20717472006599652,0.22081766267348227,0.13350217892251501],\"y\":[0.93474107917131921,0.73944327795500264,0.69561569282419511,0.63452947667216786,0.54598143166807545],\"text\":[\"COMP_N\",\"COMP_E\",\"TPG\",\"CC\",\"TP\"],\"hovertext\":[\"Policy Type: COMP_N <br>Loss Ratio: 93.5% <br>Claim Frequency: 1.043 <br>Claim Severity: $748.80 <br>Premium: $10,212,915 <br>Profit: $666,484\",\"Policy Type: COMP_E <br>Loss Ratio: 73.9% <br>Claim Frequency: 0.41 <br>Claim Severity: $990.40 <br>Premium: $35,335,541 <br>Profit: $9,206,913\",\"Policy Type: TPG <br>Loss Ratio: 69.6% <br>Claim Frequency: 0.207 <br>Claim Severity: $1,103.91 <br>Premium: $8,106,186 <br>Profit: $2,467,396\",\"Policy Type: CC <br>Loss Ratio: 63.5% <br>Claim Frequency: 0.221 <br>Claim Severity: $992.00 <br>Premium: $49,715,151 <br>Profit: $18,169,422\",\"Policy Type: TP <br>Loss Ratio: 54.6% <br>Claim Frequency: 0.134 <br>Claim Severity: $1,095.67 <br>Premium: $1,009,417 <br>Profit: $458,294\"],\"textfont\":{\"size\":13.228346456692915,\"color\":\"rgba(0,0,0,1)\"},\"type\":\"scatter\",\"mode\":\"text\",\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.059986117668633702,1.2597084710413076],\"y\":[0.70330769309343633,0.70330769309343633],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.6456692913385824,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.30730979818891813,0.30730979818891813],\"y\":[0.47499999999999998,1.0249999999999999],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.6456692913385824,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":40.840182648401829,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":48.949771689497723},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Interactive Segment Analysis by Policy Type\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.059986117668633702,1.2597084710413076],\"tickmode\":\"array\",\"ticktext\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\",\"1.25\"],\"tickvals\":[0,0.25,0.5,0.75,0.99999999999999989,1.25],\"categoryorder\":\"array\",\"categoryarray\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\",\"1.25\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Claim Frequency\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.47499999999999998,1.0249999999999999],\"tickmode\":\"array\",\"ticktext\":[\"50%\",\"60%\",\"70%\",\"80%\",\"90%\",\"100%\"],\"tickvals\":[0.5,0.59999999999999998,0.69999999999999996,0.80000000000000004,0.90000000000000002,1],\"categoryorder\":\"array\",\"categoryarray\":[\"50%\",\"60%\",\"70%\",\"80%\",\"90%\",\"100%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Loss Ratio\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Premium\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"1a618d5e7c9e\":{\"x\":{},\"y\":{},\"size\":{},\"text\":{},\"type\":\"scatter\"},\"1a61810444656\":{\"x\":{},\"y\":{},\"size\":{},\"text\":{},\"label\":{}},\"1a61851806693\":{\"yintercept\":{}},\"1a61879837fc\":{\"xintercept\":{}}},\"cur_data\":\"1a618d5e7c9e\",\"visdat\":{\"1a618d5e7c9e\":[\"function (y) \",\"x\"],\"1a61810444656\":[\"function (y) \",\"x\"],\"1a61851806693\":[\"function (y) \",\"x\"],\"1a61879837fc\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninteractive_policy_plot <- ggplot(\n  policy_type_summary,\n  aes(\n    x = claim_frequency,\n    y = loss_ratio,\n    size = premium,\n    text = paste(\n      \"Policy Type:\", policy_type,\n      \"<br>Loss Ratio:\", percent(loss_ratio, accuracy = 0.1),\n      \"<br>Claim Frequency:\", round(claim_frequency, 3),\n      \"<br>Claim Severity:\", dollar(claim_severity),\n      \"<br>Premium:\", dollar(premium),\n      \"<br>Profit:\", dollar(profit)\n    )\n  )\n) +\n  geom_point(\n    alpha = 0.75,\n    color = \"#2C7FB8\"\n  ) +\n  geom_text(\n    aes(label = policy_type),\n    vjust = -1,\n    size = 3.5,\n    show.legend = FALSE\n  ) +\n  geom_hline(\n    yintercept = portfolio_summary$overall_loss_ratio,\n    linetype = \"dashed\",\n    linewidth = 0.7\n  ) +\n  geom_vline(\n    xintercept = portfolio_summary$overall_claim_frequency,\n    linetype = \"dashed\",\n    linewidth = 0.7\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    limits = c(0.50, 1.00)\n  ) +\n  scale_x_continuous(\n    limits = c(0, max(policy_type_summary$claim_frequency) * 1.15)\n  ) +\n  scale_size_continuous(labels = dollar) +\n  labs(\n    title = \"Interactive Segment Analysis by Policy Type\",\n    subtitle = \"Hover over each point to inspect loss ratio, claim frequency, severity, premium, and profit\",\n    x = \"Claim Frequency\",\n    y = \"Loss Ratio\",\n    size = \"Premium\"\n  ) +\n  theme_minimal()\n\nggplotly(interactive_policy_plot, tooltip = \"text\")\n```\n:::\n\n:::\n\nThe interactive segment-level visualisation extends the premium adequacy quadrant by allowing users to inspect each policy type directly. Each point represents one policy type. The x-axis shows claim frequency, the y-axis shows loss ratio, and the bubble size represents premium volume. When the user hovers over a point, the tooltip displays additional information, including loss ratio, claim frequency, claim severity, premium income, and profit.\n\nThis interactive design is useful because insurance portfolio review often requires comparing multiple indicators at the same time. A static chart can show the overall pattern, but an interactive chart allows decision-makers to examine the details of each segment more efficiently. For example, COMP_E has a loss ratio of 73.9%, claim frequency of 0.41, claim severity of about \\$990, premium income of about \\$35.3 million, and profit of about \\$9.2 million. This helps show that although COMP_E has weaker-than-average profitability, it still contributes positive underwriting profit.\n\nFrom a visual analytics perspective, the interactive chart supports deeper exploration beyond dashboard reporting. It allows the analyst to move from a broad pattern to specific segment details. This is especially useful for identifying policy types that combine high premium volume, high claim frequency, and weak profitability. These segments should be prioritised for pricing review, underwriting refinement, or further claim driver investigation.\n\nOverall, the interactive chart confirms that COMP_N is the most concerning policy type because it is located in the high-frequency and high-loss-ratio area. It also shows that some policy types with weaker profitability still generate positive profit because of their premium volume. Therefore, interactive visual analytics helps balance risk, profitability, and business scale in portfolio review.\n\n::: {.insight-box}\n### Advanced Visual Analytics Insights\n\n- The risk heatmap reveals that profitability problems are concentrated in specific product-payment combinations.\n\n- The premium adequacy quadrant confirms that `COMP_N` is located in the high-frequency and high-loss-ratio area.\n\n- The interactive visualisation allows users to inspect loss ratio, claim frequency, claim severity, premium volume, and profit at the same time.\n\n- Together, these advanced visualisations move the analysis beyond simple dashboard reporting and provide more actionable support for pricing and underwriting review.\n:::\n\n## 8. Statistical Validation\n\n### 8.1 Introduction to Statistical Validation\n\nThe previous sections used visual analytics to identify important patterns in the insurance portfolio. However, visual patterns alone may be influenced by skewed distributions, uneven sample sizes, or random variation. Therefore, statistical validation is used to support the main visual findings.\n\nThe purpose of these tests is not to replace the visual analysis, but to check whether the observed relationships are statistically meaningful. Since insurance variables such as loss ratio and claim cost are highly skewed, non-parametric and categorical tests are used where appropriate.\n\n### 8.2 Kruskal-Wallis Test: Policy Type and Loss Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal_policy <- kruskal.test(loss_ratio ~ policy_type, data = motor_clean)\n\nkruskal_policy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  loss_ratio by policy_type\nKruskal-Wallis chi-squared = 7201.8, df = 4, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal_policy_result <- tibble(\n  test = \"Kruskal-Wallis test\",\n  variable = \"Policy Type\",\n  statistic = kruskal_policy$statistic,\n  p_value = kruskal_policy$p.value\n)\n\nkruskal_policy_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  test                variable    statistic p_value\n  <chr>               <chr>           <dbl>   <dbl>\n1 Kruskal-Wallis test Policy Type     7202.       0\n```\n\n\n:::\n:::\n\n\nA Kruskal-Wallis test is used to examine whether the distribution of loss ratio differs across policy types. This test is selected because loss ratio is highly skewed and does not necessarily satisfy the normality assumption required by a standard ANOVA.\n\nThe visual analysis showed that COMP_N has the highest loss ratio among all policy types, while TP has the lowest. The Kruskal-Wallis test provides statistical support for this pattern. If the p-value is statistically significant, it suggests that profitability differs across policy types and that the differences shown in the visualisation are unlikely to be due only to random variation.\n\nThis result supports the earlier finding that policy type is an important driver of portfolio profitability. In particular, COMP_N should be treated as a priority segment because it combines the highest loss ratio with the highest claim frequency.\n\n### 8.3 Chi-square Test: Fuel Type and Claim Occurrence\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuel_claim_table <- table(motor_clean$fuel_type, motor_clean$claim_indicator)\n\nfuel_claim_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n         0      1\n  D 190897  35243\n  G 110965  15233\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq_fuel <- chisq.test(fuel_claim_table)\n\nchisq_fuel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  fuel_claim_table\nX-squared = 814.55, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_fuel_result <- tibble(\n  test = \"Chi-square test\",\n  variable = \"Fuel Type\",\n  statistic = chisq_fuel$statistic,\n  p_value = chisq_fuel$p.value\n)\n\nchisq_fuel_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  test            variable  statistic   p_value\n  <chr>           <chr>         <dbl>     <dbl>\n1 Chi-square test Fuel Type      815. 3.71e-179\n```\n\n\n:::\n:::\n\n\nA chi-square test is used to examine whether claim occurrence is independent of fuel type. This test is appropriate because both fuel type and claim occurrence are categorical variables.\n\nThe visual analysis showed that diesel vehicles have higher claim frequency and higher loss ratio than gasoline vehicles, while claim severity is similar between the two groups. If the chi-square test is statistically significant, it supports the finding that claim occurrence differs by fuel type.\n\nThis result strengthens the interpretation that diesel vehicles are mainly a frequency-driven risk segment. Their weaker profitability appears to be caused more by frequent claim occurrence than by larger individual claim costs.\n\n### 8.4 Spearman Correlation: Driver Age and Loss Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspearman_driver_age <- cor.test(\n  motor_clean$driver_age,\n  motor_clean$loss_ratio,\n  method = \"spearman\"\n)\n\nspearman_driver_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  motor_clean$driver_age and motor_clean$loss_ratio\nS = 7.4737e+15, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n        rho \n-0.02562975 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspearman_driver_age_result <- tibble(\n  test = \"Spearman correlation\",\n  variable = \"Driver Age\",\n  estimate = spearman_driver_age$estimate,\n  p_value = spearman_driver_age$p.value\n)\n\nspearman_driver_age_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  test                 variable   estimate  p_value\n  <chr>                <chr>         <dbl>    <dbl>\n1 Spearman correlation Driver Age  -0.0256 2.82e-52\n```\n\n\n:::\n:::\n\n\nSpearman correlation is used to examine the relationship between driver age and loss ratio. This method is more appropriate than Pearson correlation because the relationship may not be linear and loss ratio is highly skewed.\n\nThe visual analysis showed that the relationship between driver age and profitability is not strictly linear. The 26–35, 36–45, and 66+ age groups have relatively higher loss ratios, while the 18–25 group has the lowest loss ratio. Therefore, the correlation result should be interpreted carefully.\n\nIf the test is statistically significant, it suggests that driver age is associated with loss ratio. However, correlation does not imply causation. Driver age may also be related to other factors such as vehicle value, policy type, driving licence age, or vehicle usage patterns.\n\n### 8.5 Logistic Regression for Claim Occurrence\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\nmotor_model_sample <- motor_clean %>%\n  sample_n(50000)\n\nclaim_model <- glm(\n  claim_indicator ~ driver_age + vehicle_age + vehicle_value +\n    policy_type + fuel_type + payment_frequency + circulation_area +\n    municipality_type + business_type,\n  data = motor_model_sample,\n  family = binomial\n)\n\nsummary(claim_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = claim_indicator ~ driver_age + vehicle_age + vehicle_value + \n    policy_type + fuel_type + payment_frequency + circulation_area + \n    municipality_type + business_type, family = binomial, data = motor_model_sample)\n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -2.253e+00  7.707e-02 -29.240  < 2e-16 ***\ndriver_age           1.883e-03  2.082e-03   0.905 0.365563    \nvehicle_age         -1.135e-02  2.171e-03  -5.228 1.72e-07 ***\nvehicle_value        7.354e-06  1.075e-06   6.838 8.02e-12 ***\npolicy_typeCOMP_E    4.635e-01  3.046e-02  15.216  < 2e-16 ***\npolicy_typeCOMP_N    1.153e+00  4.996e-02  23.072  < 2e-16 ***\npolicy_typeTP       -4.155e-01  1.329e-01  -3.126 0.001771 ** \npolicy_typeTPG      -3.957e-02  4.761e-02  -0.831 0.405924    \nfuel_typeG          -1.672e-01  2.966e-02  -5.638 1.72e-08 ***\npayment_frequencyQ   4.176e-01  5.640e-02   7.405 1.32e-13 ***\npayment_frequencyS   1.886e-01  3.608e-02   5.226 1.74e-07 ***\ncirculation_areaU    1.189e-01  2.658e-02   4.472 7.74e-06 ***\nmunicipality_typeI   1.041e-01  2.990e-02   3.483 0.000495 ***\nmunicipality_typeIS  1.636e-01  5.686e-02   2.877 0.004009 ** \nbusiness_typeP       4.011e-01  2.674e-02  15.001  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 41340  on 49999  degrees of freedom\nResidual deviance: 39964  on 49985  degrees of freedom\nAIC: 39994\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_result <- tidy(claim_model) %>%\n  mutate(\n    odds_ratio = exp(estimate),\n    conf_low = exp(estimate - 1.96 * std.error),\n    conf_high = exp(estimate + 1.96 * std.error)\n  ) %>%\n  select(\n    term,\n    odds_ratio,\n    conf_low,\n    conf_high,\n    p.value\n  ) %>%\n  arrange(p.value)\n\nlogit_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 5\n   term                odds_ratio conf_low conf_high   p.value\n   <chr>                    <dbl>    <dbl>     <dbl>     <dbl>\n 1 (Intercept)              0.105   0.0903     0.122 6.08e-188\n 2 policy_typeCOMP_N        3.17    2.87       3.49  8.92e-118\n 3 policy_typeCOMP_E        1.59    1.50       1.69  2.79e- 52\n 4 business_typeP           1.49    1.42       1.57  7.24e- 51\n 5 payment_frequencyQ       1.52    1.36       1.70  1.32e- 13\n 6 vehicle_value            1.00    1.00       1.00  8.02e- 12\n 7 fuel_typeG               0.846   0.798      0.897 1.72e-  8\n 8 vehicle_age              0.989   0.985      0.993 1.72e-  7\n 9 payment_frequencyS       1.21    1.13       1.30  1.74e-  7\n10 circulation_areaU        1.13    1.07       1.19  7.74e-  6\n11 municipality_typeI       1.11    1.05       1.18  4.95e-  4\n12 policy_typeTP            0.660   0.509      0.856 1.77e-  3\n13 municipality_typeIS      1.18    1.05       1.32  4.01e-  3\n14 driver_age               1.00    0.998      1.01  3.66e-  1\n15 policy_typeTPG           0.961   0.876      1.06  4.06e-  1\n```\n\n\n:::\n:::\n\n\nA logistic regression model is used as a supporting validation method for claim occurrence. The model estimates whether selected driver, vehicle, and policy characteristics are associated with the probability of having at least one claim after controlling for other variables.\n\nBecause the full dataset is large, a random sample of 50,000 observations is used for this validation model. The purpose of the model is not to build a full predictive model, but to support the visual analytics findings. The output is reported using odds ratios. An odds ratio above 1 indicates higher odds of having a claim, while an odds ratio below 1 indicates lower odds of having a claim.\n\nThis model helps check whether the visual findings remain meaningful when several variables are analysed together. For example, if policy type, fuel type, or payment frequency remains statistically significant, it supports the earlier segment-level findings that these variables are associated with claim risk.\n\n## 9. Key Findings\n\nThe visual analytics reveal several important findings about the motor insurance portfolio.\n\nFirst, the portfolio is profitable overall, but profitability deteriorates over time. The yearly loss ratio increased from 65.7% in 2022 to 66.5% in 2023 and then to 74.7% in 2024. Although the loss ratio remains below the 100% break-even threshold, the upward trend indicates that the underwriting margin became thinner in 2024.\n\nSecond, both premium income and incurred claims increased from 2022 to 2024. However, incurred claims grew faster relative to premium income, especially in 2024. This explains why the portfolio loss ratio increased. Business growth alone does not guarantee stronger profitability if claim costs grow faster than premium income.\n\nThird, claim costs are highly concentrated. The claim concentration curve shows that a small share of high-loss policies contributes a large share of total incurred claims. This means that portfolio volatility is strongly influenced by tail-risk observations rather than only by average claim behaviour.\n\nFourth, the frequency-severity decomposition shows that claim frequency increased steadily from 2022 to 2024, while claim severity decreased in 2023 but rebounded in 2024. Therefore, the deterioration in 2024 profitability appears to be driven by both higher claim frequency and a rebound in average claim size.\n\nFifth, policy type is a major driver of profitability. COMP_N has the highest loss ratio at 93.5% and the highest claim frequency at 1.04. This makes COMP_N the most concerning policy type because it combines weak profitability with frequent claim occurrence.\n\nSixth, policy status is strongly associated with profitability. Policy status C has a loss ratio of 128.0%, which is above the 100% break-even threshold. This means that claim costs exceed premium income for this segment. In contrast, policy status A has a much lower loss ratio of 64.5%.\n\nSeventh, payment frequency is associated with different profitability patterns. Annual payment policies have the lowest loss ratio at 67.9%, while quarterly and semi-annual payment policies have higher loss ratios of 76.4% and 80.7%, respectively. This suggests that non-annual payment groups may have weaker profitability.\n\nEighth, diesel vehicles show weaker profitability than gasoline vehicles, but the difference is mainly frequency-driven. Diesel vehicles have a higher claim frequency of 0.342 compared with 0.246 for gasoline vehicles. However, claim severity is almost identical between the two groups, at approximately $959 for diesel vehicles and $960 for gasoline vehicles. This suggests that diesel vehicles do not generate more expensive claims on average; instead, they generate claims more often.\n\nNinth, driver age and vehicle age show non-linear profitability patterns. For driver age, the 26–35, 36–45, and 66+ groups have relatively higher loss ratios, while the 18–25 group has the lowest loss ratio. For vehicle age, the 0–5 and 11–20 groups show weaker profitability than older vehicle groups.\n\nFinally, the advanced visual analytics reveal more specific high-risk combinations. The risk heatmap shows that COMP_N policies with semi-annual payment have a loss ratio of 108.8%, making this segment loss-making. The premium adequacy quadrant also confirms that COMP_N is located in the high-frequency and high-loss-ratio area.\n\n## 10. Business Implications\n\nThe findings provide several practical implications for insurance portfolio management.\n\nFirst, COMP_N should be prioritised for pricing and underwriting review. It has the highest loss ratio and the highest claim frequency among all policy types. This suggests that the premium charged for COMP_N may not fully reflect its claim occurrence risk. The insurer should further examine the customer profile, vehicle characteristics, coverage design, and underwriting rules associated with this policy type.\n\nSecond, the insurer should pay particular attention to COMP_N policies with semi-annual payment frequency. The risk heatmap shows that this specific segment has a loss ratio of 108.8%, which means it is loss-making. This finding shows the value of segment-level visual analytics. The problem is not only COMP_N as a broad policy type, but more specifically COMP_N combined with semi-annual payment.\n\nThird, policy status C requires further investigation. Its loss ratio is 128.0%, which means claim costs exceed premium income. The insurer should examine whether policy closure or cancellation is related to adverse claim experience. If customers with poor claim experience are more likely to enter status C, this may indicate retention risk or adverse selection.\n\nFourth, the rising yearly loss ratio suggests that the insurer should monitor pricing adequacy over time. The portfolio remains profitable, but the margin of profitability became smaller in 2024. If claim frequency or claim severity continues to increase, premium adjustments or underwriting refinements may be necessary.\n\nFifth, the claim concentration result suggests that tail-risk monitoring should be included in regular portfolio review. A small number of large-loss policies can have a significant effect on total incurred claims. Therefore, large-loss policies should be analysed separately to identify whether they are concentrated in specific policy types, vehicle age groups, fuel types, or payment frequency groups.\n\nSixth, diesel vehicles should be monitored as a frequency-driven risk segment. The analysis shows that diesel vehicles have higher claim frequency and higher loss ratio than gasoline vehicles, while claim severity is almost the same. This means the insurer should investigate vehicle usage intensity, customer driving patterns, exposure characteristics, or policy type composition for diesel vehicles, rather than focusing only on repair cost per claim.\n\nFinally, non-annual payment groups should also be monitored as potential risk indicators. Quarterly and semi-annual payment groups have higher loss ratios than annual payment policies. This result should not be interpreted as causal evidence, but it provides a useful segmentation signal for further underwriting and pricing investigation.\n\n## 11. Limitations\n\nThis study has several limitations.\n\nFirst, the analysis is exploratory and focuses on associations rather than causal effects. For example, the finding that COMP_N has a higher loss ratio does not prove that the policy type itself causes higher claims. The result may also reflect differences in customer profiles, vehicle characteristics, coverage design, or exposure patterns.\n\nSecond, some variables are coded categories and require deeper business interpretation. Without full internal documentation from the insurer, the exact business meaning of some categories may not be fully clear.\n\nThird, the dataset does not include external factors such as repair cost inflation, regional traffic density, weather conditions, fraud risk, or macroeconomic conditions. These external factors may also affect claim frequency and claim severity.\n\nFourth, the logistic regression model is used only as a supporting validation method. It is not intended to be a full predictive model. A more advanced predictive modelling framework could be developed in future work to estimate claim probability, claim severity, or expected loss more accurately.\n\nFinally, some charts aggregate policies into broad groups, such as driver age groups and vehicle age groups. While grouping improves readability, it may hide variation within each group.\n\n## 12. Conclusion\n\nIn conclusion, this take-home exercise demonstrates how visual analytics can be used to investigate profitability, claim volatility, and high-risk segments in a motor insurance portfolio.\n\nThe analysis shows that the portfolio is profitable overall, but profitability deteriorated from 2022 to 2024. The loss ratio increased to 74.7% in 2024, indicating that claim costs became heavier relative to premium income. Frequency-severity decomposition further shows that this deterioration is related to both higher claim frequency and a rebound in claim severity.\n\nThe segment-level analysis reveals that profitability problems are not evenly distributed across the portfolio. COMP_N is the most concerning policy type because it has both the highest loss ratio and the highest claim frequency. Policy status C is also a clear loss-making segment, with a loss ratio of 128.0%. Payment frequency, driver age, vehicle age, and fuel type also provide useful segmentation signals.\n\nThe fuel type analysis shows the value of separating claim frequency from claim severity. Diesel vehicles have weaker profitability than gasoline vehicles, but their claim severity is almost identical. Their weaker performance is mainly driven by more frequent claim occurrence rather than larger individual claim costs. This demonstrates why frequency-severity decomposition is important for insurance portfolio analysis.\n\nThe advanced visual analytics provide more detailed insights. The risk heatmap identifies COMP_N with semi-annual payment as a specific loss-making segment, while the premium adequacy quadrant confirms that COMP_N is located in the high-frequency and high-loss-ratio area. The interactive chart further supports exploratory investigation by allowing users to inspect loss ratio, claim frequency, claim severity, premium volume, and profit at the segment level.\n\nOverall, this report shows that visual analytics can move insurance analysis beyond simple dashboard reporting. It helps identify where profitability problems are concentrated, explains whether weak performance is frequency-driven or severity-driven, and supports more targeted underwriting, pricing, and portfolio management decisions.\n\nOverall, this report shows that visual analytics can move insurance analysis beyond simple dashboard reporting. It helps identify where profitability problems are concentrated, explains whether weak performance is frequency-driven or severity-driven, and supports more targeted underwriting, pricing, and portfolio management decisions.\n\n## 13 References and Inspiration\n\n- [R for Visual Analytics.](https://r4va.netlify.app/)\n\n- [R for Data Science.](https://r4ds.hadley.nz/)\n\n- [Fundamentals of Data Visualisation.](https://clauswilke.com/dataviz/)\n\n- [ggplot2: Elegant Graphics for Data Analysis.](https://ggplot2-book.org/)\n\n- [Plotly R Documentation.](https://plotly.com/r/)\n\n- [Tidyverse Documentation.](https://www.tidyverse.org/)\n\n- [Quarto HTML Documentation.](https://quarto.org/docs/output-formats/html-basics.html)\n\n- [Quarto Revealjs Documentation.](https://quarto.org/docs/presentations/revealjs/)\n\n\n",
    "supporting": [
      "Take-Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.12/grViz.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}